# Site Settings
title: Jeanniffer Pimentel
email: jeannifferpimentel@gmail.com
description: >
  Portafolio - Jeanniffer Pimentel
baseurl: ""
url: "http://localhost:4000"
twitter_username: jeanniferpl
github_username: jeanniffer
# Build Settings
sass:
  sass_dir: _sass
include: ["_pages"]
kramdown:
  input: GFM
